apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sender-worker
  namespace: norify
spec:
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 3
  maxReplicaCount: 20
  scaleTargetRef:
    name: sender-worker
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: message.send.request
        mode: QueueLength
        value: "100"
        hostFromEnv: RABBITMQ_URL
